root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ."
bin = "./tmp/main"
include_ext = ["go"]
exclude_dir = ["tmp", "vendor"]
delay = 1000 # ms

[log]
time = true

[screen]
clear_on_rebuild = true
